### ISSUE TITLE
Can I run it on windows?

### ISSUE THREAD

**Issue by y1131388949** [mmahdavian/STPOTR#6]
Can I run it on windows? Or is there a requirements.txt I'm using 4080ti and the cuda11.1 in the stpotr.yml file doesn't seem to work!

**Comment by mmahdavian** [comment]
Hi @y1131388949 . I think you can install anaconda on windows as well and use the package.

**Comment by y1131388949** [comment]
When I run the testing.py file, I get the following error:
Traceback (most recent call last):
  File "D:/Project/STPOTR/models/testing.py", line 553, in <module>
    Calc_error_h36mdataset()
  File "D:/Project/STPOTR/models/testing.py", line 170, in Calc_error_h36mdataset
    sample = next(iter(eval_dataset_fn))
  File "D:\Anaconda3\envs\transformer\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\envs\transformer\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\transformer\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'dict_keys' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Anaconda3\envs\transformer\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by mmahdavian** [comment]
@y1131388949 please make sure you are using correct data files and correct version for the packages based on the stpotr.yaml file.
